kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "deephealth-backend.name" . }}-role
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/part-of: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
rules:
- apiGroups: ["", "extensions", "apps", "batch", "secrets"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "deephealth-backend.name" . }}-rbac
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/part-of: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: {{ include "deephealth-backend.name" . }}-role
  apiGroup: rbac.authorization.k8s.io